package tasks

func errFunc(err error) {
	panic(err)
}
